from django.urls import path

from .workflows.lldp_consistency.views import LLDPConsistencyCheckView
from .workflows.vlan_deployment.views import VLANDeploymentView, GetCommonInterfacesView, GetVLANsBySiteView, GetInterfacesForSyncView, VLANDeploymentJobsView, VLANDeploymentJobDetailView
from .workflows.netbox_vlan_tagging.views import VLANTaggingView
from .workflows.maas_openstack_sync.views import (
    MAASOpenStackSyncView,
    DriftAuditDownloadXlsxView,
    DriftAuditDownloadXlsxModifiedView,
)
from .workflows.maas_openstack_sync.history_views import (
    MAASOpenStackSyncRunsView,
    MAASOpenStackSyncRunDetailView,
    MAASOpenStackSyncRunDownloadXlsxView,
    MAASOpenStackSyncRunSaveReviewView,
)
from .sync.reconciliation.views import (
    ReconciliationApplyResultsView,
    ReconciliationApplyView,
    ReconciliationBranchPgSchemaStatusView,
    ReconciliationCreateView,
    ReconciliationDiscardView,
    ReconciliationNotImplementedPostView,
    ReconciliationPreviewView,
    ReconciliationRecheckBranchView,
    ReconciliationRetryFailedView,
    ReconciliationRunDetailView,
    ReconciliationRunsListView,
    ReconciliationStagingView,
)

app_name = "netbox_automation_plugin"

urlpatterns = [
    path(
        "lldp-consistency-check/",
        LLDPConsistencyCheckView.as_view(),
        name="lldp_consistency_check",
    ),
    path(
        "vlan-deployment/",
        VLANDeploymentView.as_view(),
        name="vlan_deployment",
    ),
    path(
        "vlan-deployment/jobs/",
        VLANDeploymentJobsView.as_view(),
        name="vlan_deployment_jobs",
    ),
    path(
        "vlan-deployment/jobs/<int:job_id>/",
        VLANDeploymentJobDetailView.as_view(),
        name="vlan_deployment_job_detail",
    ),
    path(
        "vlan-deployment/get-interfaces/",
        GetCommonInterfacesView.as_view(),
        name="vlan_deployment_get_interfaces",
    ),
    path(
        "vlan-deployment/get-interfaces-for-sync/",
        GetInterfacesForSyncView.as_view(),
        name="vlan_deployment_get_interfaces_for_sync",
    ),
    path(
        "vlan-deployment/get-vlans/",
        GetVLANsBySiteView.as_view(),
        name="vlan_deployment_get_vlans",
    ),
    path(
        "netbox-vlan-tagging/",
        VLANTaggingView.as_view(),
        name="netbox_vlan_tagging",
    ),
    path(
        "maas-openstack-sync/",
        MAASOpenStackSyncView.as_view(),
        name="maas_openstack_sync",
    ),
    path(
        "maas-openstack-sync/download-xlsx/",
        DriftAuditDownloadXlsxView.as_view(),
        name="maas_openstack_sync_download_xlsx",
    ),
    path(
        "maas-openstack-sync/download-xlsx-modified/",
        DriftAuditDownloadXlsxModifiedView.as_view(),
        name="maas_openstack_sync_download_xlsx_modified",
    ),
    path(
        "maas-openstack-sync/runs/",
        MAASOpenStackSyncRunsView.as_view(),
        name="maas_openstack_sync_runs",
    ),
    path(
        "maas-openstack-sync/runs/<int:run_id>/",
        MAASOpenStackSyncRunDetailView.as_view(),
        name="maas_openstack_sync_run_detail",
    ),
    path(
        "maas-openstack-sync/runs/<int:run_id>/download-xlsx/",
        MAASOpenStackSyncRunDownloadXlsxView.as_view(),
        name="maas_openstack_sync_run_download_xlsx",
    ),
    path(
        "maas-openstack-sync/runs/<int:run_id>/save-review/",
        MAASOpenStackSyncRunSaveReviewView.as_view(),
        name="maas_openstack_sync_run_save_review",
    ),
    path(
        "maas-openstack-sync/reconciliation/runs/",
        ReconciliationRunsListView.as_view(),
        name="maas_openstack_reconciliation_runs",
    ),
    path(
        "maas-openstack-sync/reconciliation/runs/<int:run_id>/",
        ReconciliationRunDetailView.as_view(),
        name="maas_openstack_reconciliation_detail",
    ),
    path(
        "maas-openstack-sync/reconciliation/runs/<int:run_id>/apply-results/",
        ReconciliationApplyResultsView.as_view(),
        name="maas_openstack_reconciliation_apply_results",
    ),
    path(
        "maas-openstack-sync/reconciliation/runs/<int:run_id>/branch-pg-schema-status/",
        ReconciliationBranchPgSchemaStatusView.as_view(),
        name="maas_openstack_reconciliation_branch_pg_schema_status",
    ),
    path(
        "maas-openstack-sync/reconciliation/stage/",
        ReconciliationStagingView.as_view(),
        name="maas_openstack_reconciliation_stage",
    ),
    path(
        "maas-openstack-sync/reconciliation/preview/",
        ReconciliationPreviewView.as_view(),
        name="maas_openstack_reconciliation_preview",
    ),
    path(
        "maas-openstack-sync/reconciliation/create/",
        ReconciliationCreateView.as_view(),
        name="maas_openstack_reconciliation_create",
    ),
    path(
        "maas-openstack-sync/reconciliation/runs/<int:run_id>/apply/",
        ReconciliationApplyView.as_view(),
        name="maas_openstack_reconciliation_apply",
    ),
    path(
        "maas-openstack-sync/reconciliation/runs/<int:run_id>/retry-failed/",
        ReconciliationRetryFailedView.as_view(),
        name="maas_openstack_reconciliation_retry_failed",
    ),
    path(
        "maas-openstack-sync/reconciliation/runs/<int:run_id>/recheck-branch/",
        ReconciliationRecheckBranchView.as_view(),
        name="maas_openstack_reconciliation_recheck_branch",
    ),
    path(
        "maas-openstack-sync/reconciliation/runs/<int:run_id>/validate/",
        ReconciliationNotImplementedPostView.as_view(),
        name="maas_openstack_reconciliation_validate",
    ),
    path(
        "maas-openstack-sync/reconciliation/runs/<int:run_id>/merge/",
        ReconciliationNotImplementedPostView.as_view(),
        name="maas_openstack_reconciliation_merge",
    ),
    path(
        "maas-openstack-sync/reconciliation/runs/<int:run_id>/discard/",
        ReconciliationDiscardView.as_view(),
        name="maas_openstack_reconciliation_discard",
    ),
]


